services:
  - type: web
    name: casaborda-inventario
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
